# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/subhagato/Codes/smartheadlight_fpga/CameraLinkTest/CameraLinkTest.srcs/sources_1/bd/design_1/Cameralink_deca.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: bd/design_1/ip/design_1_cameralink_to_axis_0_1/design_1_cameralink_to_axis_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_cameralink_to_axis_0_1 || ORIG_REF_NAME==design_1_cameralink_to_axis_0_1}]

# IP: bd/design_1/ip/design_1_cameralink_to_axis_0_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==v_vid_in_axi4s_0 || ORIG_REF_NAME==v_vid_in_axi4s_0}]

# XDC: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_vio_0_0/design_1_vio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_vio_0_0 || ORIG_REF_NAME==design_1_vio_0_0}]

# XDC: bd/design_1/ip/design_1_cameralink_to_axis_0_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_cameralink_to_axis_0_1/ip/v_vid_in_axi4s_0/v_vid_in_axi4s_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==v_vid_in_axi4s_0 || ORIG_REF_NAME==v_vid_in_axi4s_0}] {/inst }]/inst ]]

# XDC: bd/design_1/design_1_ooc.xdc
