webtalk_init -webtalk_dir /home/subhagato/Codes/smartheadlight_fpga/CameraLinkTest_backup/CameraLinkTest.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul  6 14:14:50 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2014.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1071353" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174679548_176449548_210570730_342" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b5da12db-d798-4d1b-84da-739c6dcd9748" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cbe22f4a-2eee-4085-8ead-d693c139e6ee" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 12.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key cable -value "Xilinx/DLC10/6000000" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "000040001372C093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_transmit -clientid 280424407 -regid "174679548_176449548_210570730_342" -xml /home/subhagato/Codes/smartheadlight_fpga/CameraLinkTest_backup/CameraLinkTest.hw/webtalk/usage_statistics_ext_labtool.xml -html /home/subhagato/Codes/smartheadlight_fpga/CameraLinkTest_backup/CameraLinkTest.hw/webtalk/usage_statistics_ext_labtool.html -wdm /home/subhagato/Codes/smartheadlight_fpga/CameraLinkTest_backup/CameraLinkTest.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
