// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_synchr_strm,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=2.740000,HLS_SYN_LAT=1,HLS_SYN_TPT=2,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=8,HLS_SYN_LUT=9}" *)

module hls_synchr_strm (
        src_V_V_TDATA,
        dst_V_V_TDATA,
        start_sig,
        start_sigo,
        ap_clk,
        ap_rst_n,
        src_V_V_TVALID,
        src_V_V_TREADY,
        dst_V_V_TVALID,
        dst_V_V_TREADY,
        start_sigo_ap_vld
);

parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_true = 1'b1;

input  [63:0] src_V_V_TDATA;
output  [63:0] dst_V_V_TDATA;
input   start_sig;
output   start_sigo;
input   ap_clk;
input   ap_rst_n;
input   src_V_V_TVALID;
output   src_V_V_TREADY;
output   dst_V_V_TVALID;
input   dst_V_V_TREADY;
output   start_sigo_ap_vld;

reg    ap_rst_n_inv;
wire    hls_synchr_strm_Block_proc_U0_ap_start;
wire    hls_synchr_strm_Block_proc_U0_ap_done;
wire    hls_synchr_strm_Block_proc_U0_ap_continue;
wire    hls_synchr_strm_Block_proc_U0_ap_idle;
wire    hls_synchr_strm_Block_proc_U0_ap_ready;
wire   [0:0] hls_synchr_strm_Block_proc_U0_start_sig;
wire   [63:0] hls_synchr_strm_Block_proc_U0_src_V_V_TDATA;
wire    hls_synchr_strm_Block_proc_U0_src_V_V_TVALID;
wire    hls_synchr_strm_Block_proc_U0_src_V_V_TREADY;
wire   [63:0] hls_synchr_strm_Block_proc_U0_dst_V_V_TDATA;
wire    hls_synchr_strm_Block_proc_U0_dst_V_V_TVALID;
wire    hls_synchr_strm_Block_proc_U0_dst_V_V_TREADY;
wire   [0:0] hls_synchr_strm_Block_proc_U0_start_sigo;
wire    hls_synchr_strm_Block_proc_U0_start_sigo_ap_vld;
wire    ap_sig_hs_continue;
reg    ap_CS;
reg    ap_sig_hs_done;


hls_synchr_strm_Block_proc hls_synchr_strm_Block_proc_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( hls_synchr_strm_Block_proc_U0_ap_start ),
    .ap_done( hls_synchr_strm_Block_proc_U0_ap_done ),
    .ap_continue( hls_synchr_strm_Block_proc_U0_ap_continue ),
    .ap_idle( hls_synchr_strm_Block_proc_U0_ap_idle ),
    .ap_ready( hls_synchr_strm_Block_proc_U0_ap_ready ),
    .start_sig( hls_synchr_strm_Block_proc_U0_start_sig ),
    .src_V_V_TDATA( hls_synchr_strm_Block_proc_U0_src_V_V_TDATA ),
    .src_V_V_TVALID( hls_synchr_strm_Block_proc_U0_src_V_V_TVALID ),
    .src_V_V_TREADY( hls_synchr_strm_Block_proc_U0_src_V_V_TREADY ),
    .dst_V_V_TDATA( hls_synchr_strm_Block_proc_U0_dst_V_V_TDATA ),
    .dst_V_V_TVALID( hls_synchr_strm_Block_proc_U0_dst_V_V_TVALID ),
    .dst_V_V_TREADY( hls_synchr_strm_Block_proc_U0_dst_V_V_TREADY ),
    .start_sigo( hls_synchr_strm_Block_proc_U0_start_sigo ),
    .start_sigo_ap_vld( hls_synchr_strm_Block_proc_U0_start_sigo_ap_vld )
);



/// assign process. ///
always @(posedge ap_clk)
begin
    ap_CS <= ap_const_logic_0;
end

/// ap_sig_hs_done assign process. ///
always @ (hls_synchr_strm_Block_proc_U0_ap_done)
begin
    if ((hls_synchr_strm_Block_proc_U0_ap_done == ap_const_logic_1)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

/// ap_rst_n_inv assign process. ///
always @ (ap_rst_n)
begin
    ap_rst_n_inv = ~ap_rst_n;
end
assign ap_sig_hs_continue = ap_const_logic_0;
assign dst_V_V_TDATA = hls_synchr_strm_Block_proc_U0_dst_V_V_TDATA;
assign dst_V_V_TVALID = hls_synchr_strm_Block_proc_U0_dst_V_V_TVALID;
assign hls_synchr_strm_Block_proc_U0_ap_continue = ap_const_logic_1;
assign hls_synchr_strm_Block_proc_U0_ap_start = ap_const_logic_1;
assign hls_synchr_strm_Block_proc_U0_dst_V_V_TREADY = dst_V_V_TREADY;
assign hls_synchr_strm_Block_proc_U0_src_V_V_TDATA = src_V_V_TDATA;
assign hls_synchr_strm_Block_proc_U0_src_V_V_TVALID = src_V_V_TVALID;
assign hls_synchr_strm_Block_proc_U0_start_sig = start_sig;
assign src_V_V_TREADY = hls_synchr_strm_Block_proc_U0_src_V_V_TREADY;
assign start_sigo = hls_synchr_strm_Block_proc_U0_start_sigo;
assign start_sigo_ap_vld = hls_synchr_strm_Block_proc_U0_start_sigo_ap_vld;


endmodule //hls_synchr_strm

